import * as Types from '../../../../../types/notifications/graphql-base';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

export type GetNotificationSettingsQueryVariables = Types.Exact<{
    workspaceId: Types.Scalars['ID']['input'];
}>;

export type GetNotificationSettingsQuery = { __typename?: 'Query', workspaceNotificationSettings?: { __typename?: 'NotificationSettingsType', id: string, inAppSoundEnabled?: boolean | null, inAppBrowserNotifications?: boolean | null, quietHoursEnabled?: boolean | null, quietHoursStart?: string | null, quietHoursEnd?: string | null, inAppEvents?: any | null, notificationEvents?: any | null } | null };

export const GetNotificationSettingsDocument = { "kind": "Document", "definitions": [{ "kind": "OperationDefinition", "operation": "query", "name": { "kind": "Name", "value": "GetNotificationSettings" }, "variableDefinitions": [{ "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "workspaceId" } }, "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "ID" } } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "workspaceNotificationSettings" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "workspaceId" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "workspaceId" } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "id" } }, { "kind": "Field", "name": { "kind": "Name", "value": "inAppSoundEnabled" } }, { "kind": "Field", "name": { "kind": "Name", "value": "inAppBrowserNotifications" } }, { "kind": "Field", "name": { "kind": "Name", "value": "quietHoursEnabled" } }, { "kind": "Field", "name": { "kind": "Name", "value": "quietHoursStart" } }, { "kind": "Field", "name": { "kind": "Name", "value": "quietHoursEnd" } }, { "kind": "Field", "name": { "kind": "Name", "value": "inAppEvents" } }, { "kind": "Field", "name": { "kind": "Name", "value": "notificationEvents" } }] } }] } }] } as unknown as DocumentNode<GetNotificationSettingsQuery, GetNotificationSettingsQueryVariables>;
