import * as Types from '../../../../../../types/subscription/graphql-base';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type GetPlansQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type GetPlansQuery = { __typename?: 'Query', isIntroPricingEligible: boolean | null, plans: Array<{ __typename?: 'PlanType', id: string, tier: Types.SubscriptionSubscriptionPlanTierChoices, name: string, description: string, introPrice: number | null, introDurationDays: number | null, regularPriceMonthly: number | null, regularPriceYearly: number | null, showcase: { __typename?: 'PlanShowcaseType', order: number | null, nameOverride: string | null, tagline: string | null, highlightedFeatures: Array<string | null> | null, badge: { __typename?: 'PlanBadgeType', text: string | null, tone: string | null } | null, pricingDisplay: { __typename?: 'PlanPricingDisplayType', mode: string | null, introLabel: string | null, introSuffix: string | null, startingLabel: string | null, hasIntroDiscount: boolean | null, supportsYearlyBilling: boolean | null } | null, cta: { __typename?: 'PlanCTAType', default: string | null, currentPlan: string | null } | null } | null } | null> | null };


export const GetPlansDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetPlans"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"plans"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"tier"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"introPrice"}},{"kind":"Field","name":{"kind":"Name","value":"introDurationDays"}},{"kind":"Field","name":{"kind":"Name","value":"regularPriceMonthly"}},{"kind":"Field","name":{"kind":"Name","value":"regularPriceYearly"}},{"kind":"Field","name":{"kind":"Name","value":"showcase"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"order"}},{"kind":"Field","name":{"kind":"Name","value":"nameOverride"}},{"kind":"Field","name":{"kind":"Name","value":"tagline"}},{"kind":"Field","name":{"kind":"Name","value":"badge"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"text"}},{"kind":"Field","name":{"kind":"Name","value":"tone"}}]}},{"kind":"Field","name":{"kind":"Name","value":"pricingDisplay"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"mode"}},{"kind":"Field","name":{"kind":"Name","value":"introLabel"}},{"kind":"Field","name":{"kind":"Name","value":"introSuffix"}},{"kind":"Field","name":{"kind":"Name","value":"startingLabel"}},{"kind":"Field","name":{"kind":"Name","value":"hasIntroDiscount"}},{"kind":"Field","name":{"kind":"Name","value":"supportsYearlyBilling"}}]}},{"kind":"Field","name":{"kind":"Name","value":"cta"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"default"}},{"kind":"Field","name":{"kind":"Name","value":"currentPlan"}}]}},{"kind":"Field","name":{"kind":"Name","value":"highlightedFeatures"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"isIntroPricingEligible"}}]}}]} as unknown as DocumentNode<GetPlansQuery, GetPlansQueryVariables>;