import * as Types from '../../../../../../types/workspace/store/graphql-base';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type GetCustomerAdvisoryProfileQueryVariables = Types.Exact<{
  customerPhone: Types.Scalars['String']['input'];
}>;


export type GetCustomerAdvisoryProfileQuery = { __typename?: 'Query', customerAdvisoryProfile: { __typename?: 'CustomerAdvisoryProfileType', id: string, customerPhone: string, aiScore: number | null, conversionProbability: number, dropRisk: number, dropRiskLevel: Types.WorkmanCustomerAdvisoryProfileDropRiskLevelChoices, priceSensitivity: number, decisiveness: number, trustLevel: number, currentIntent: Types.WorkmanCustomerAdvisoryProfileCurrentIntentChoices, intentConfidence: number, activeIntervention: Types.WorkmanCustomerAdvisoryProfileActiveInterventionChoices, messageCount: number, lastAnalyzedAt: string | null, isStale: boolean, sentimentHistory: any | null, lastAdviserOutput: any | null, currentDomain: Types.WorkmanCustomerAdvisoryProfileCurrentDomainChoices, currentState: string, previousState: string | null, isStateTransitionPaused: boolean, pauseReason: string | null } | null };


export const GetCustomerAdvisoryProfileDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetCustomerAdvisoryProfile"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"customerPhone"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"customerAdvisoryProfile"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"customerPhone"},"value":{"kind":"Variable","name":{"kind":"Name","value":"customerPhone"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"customerPhone"}},{"kind":"Field","name":{"kind":"Name","value":"aiScore"}},{"kind":"Field","name":{"kind":"Name","value":"conversionProbability"}},{"kind":"Field","name":{"kind":"Name","value":"dropRisk"}},{"kind":"Field","name":{"kind":"Name","value":"dropRiskLevel"}},{"kind":"Field","name":{"kind":"Name","value":"priceSensitivity"}},{"kind":"Field","name":{"kind":"Name","value":"decisiveness"}},{"kind":"Field","name":{"kind":"Name","value":"trustLevel"}},{"kind":"Field","name":{"kind":"Name","value":"currentIntent"}},{"kind":"Field","name":{"kind":"Name","value":"intentConfidence"}},{"kind":"Field","name":{"kind":"Name","value":"activeIntervention"}},{"kind":"Field","name":{"kind":"Name","value":"messageCount"}},{"kind":"Field","name":{"kind":"Name","value":"lastAnalyzedAt"}},{"kind":"Field","name":{"kind":"Name","value":"isStale"}},{"kind":"Field","name":{"kind":"Name","value":"sentimentHistory"}},{"kind":"Field","name":{"kind":"Name","value":"lastAdviserOutput"}},{"kind":"Field","name":{"kind":"Name","value":"currentDomain"}},{"kind":"Field","name":{"kind":"Name","value":"currentState"}},{"kind":"Field","name":{"kind":"Name","value":"previousState"}},{"kind":"Field","name":{"kind":"Name","value":"isStateTransitionPaused"}},{"kind":"Field","name":{"kind":"Name","value":"pauseReason"}}]}}]}}]} as unknown as DocumentNode<GetCustomerAdvisoryProfileQuery, GetCustomerAdvisoryProfileQueryVariables>;