import * as Types from '../../../../../../types/themes/graphql-base';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type ThemeDetailsQueryVariables = Types.Exact<{
  slug: Types.Scalars['String']['input'];
}>;


export type ThemeDetailsQuery = { __typename?: 'Query', themeDetails: { __typename?: 'ThemeDetailsType', id: string, name: string, slug: string, description: string, author: string, version: string, templateType: Types.ThemeTemplateTemplateTypeChoices, workspaceTypes: any, priceTier: Types.ThemeTemplatePriceTierChoices, priceAmount: string | null, previewImage: string, demoUrl: string, tags: any, compatibility: any, viewCount: number, downloadCount: number, activeUsageCount: number, createdAt: string, updatedAt: string, showcaseSections: Array<{ __typename?: 'ShowcaseSectionType', title: string | null, description: string | null, image: string | null } | null> | null, features: Array<{ __typename?: 'FeatureCategoryType', category: string | null, items: Array<string | null> | null } | null> | null } | null };


export const ThemeDetailsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"ThemeDetails"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"slug"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"themeDetails"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"slug"},"value":{"kind":"Variable","name":{"kind":"Name","value":"slug"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"slug"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"author"}},{"kind":"Field","name":{"kind":"Name","value":"version"}},{"kind":"Field","name":{"kind":"Name","value":"templateType"}},{"kind":"Field","name":{"kind":"Name","value":"workspaceTypes"}},{"kind":"Field","name":{"kind":"Name","value":"priceTier"}},{"kind":"Field","name":{"kind":"Name","value":"priceAmount"}},{"kind":"Field","name":{"kind":"Name","value":"previewImage"}},{"kind":"Field","name":{"kind":"Name","value":"demoUrl"}},{"kind":"Field","name":{"kind":"Name","value":"showcaseSections"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"title"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"image"}}]}},{"kind":"Field","name":{"kind":"Name","value":"features"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"category"}},{"kind":"Field","name":{"kind":"Name","value":"items"}}]}},{"kind":"Field","name":{"kind":"Name","value":"tags"}},{"kind":"Field","name":{"kind":"Name","value":"compatibility"}},{"kind":"Field","name":{"kind":"Name","value":"viewCount"}},{"kind":"Field","name":{"kind":"Name","value":"downloadCount"}},{"kind":"Field","name":{"kind":"Name","value":"activeUsageCount"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}}]}}]}}]} as unknown as DocumentNode<ThemeDetailsQuery, ThemeDetailsQueryVariables>;