import * as Types from '../../../../../../types/hosting/graphql-base';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type CustomDomainQueryVariables = Types.Exact<{
  domainId: Types.Scalars['ID']['input'];
}>;


export type CustomDomainQuery = { __typename?: 'Query', customDomain: { __typename?: 'CustomDomainDetailType', id: string, domain: string, status: Types.WorkspaceHostingCustomDomainStatusChoices, dnsStatus: string, tlsStatus: string, registrarName: Types.WorkspaceHostingCustomDomainRegistrarNameChoices | null, createdAt: string, verifiedAt: string | null, sslEnabled: boolean, sslProvisionedAt: string | null, dnsRecordsToRemove: Array<{ __typename?: 'DNSRecordType', type: string, name: string, currentValue: string | null, updateTo: string | null, action: string } | null> | null, dnsRecordsToAdd: Array<{ __typename?: 'DNSRecordType', type: string, name: string, currentValue: string | null, updateTo: string | null, action: string } | null> | null, dnsRecordsToUpdate: Array<{ __typename?: 'DNSRecordType', type: string, name: string, currentValue: string | null, updateTo: string | null, action: string } | null> | null } | null };


export const CustomDomainDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"CustomDomain"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"domainId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"customDomain"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"domainId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"domainId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"domain"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"dnsStatus"}},{"kind":"Field","name":{"kind":"Name","value":"tlsStatus"}},{"kind":"Field","name":{"kind":"Name","value":"registrarName"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"verifiedAt"}},{"kind":"Field","name":{"kind":"Name","value":"sslEnabled"}},{"kind":"Field","name":{"kind":"Name","value":"sslProvisionedAt"}},{"kind":"Field","name":{"kind":"Name","value":"dnsRecordsToRemove"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"currentValue"}},{"kind":"Field","name":{"kind":"Name","value":"updateTo"}},{"kind":"Field","name":{"kind":"Name","value":"action"}}]}},{"kind":"Field","name":{"kind":"Name","value":"dnsRecordsToAdd"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"currentValue"}},{"kind":"Field","name":{"kind":"Name","value":"updateTo"}},{"kind":"Field","name":{"kind":"Name","value":"action"}}]}},{"kind":"Field","name":{"kind":"Name","value":"dnsRecordsToUpdate"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"currentValue"}},{"kind":"Field","name":{"kind":"Name","value":"updateTo"}},{"kind":"Field","name":{"kind":"Name","value":"action"}}]}}]}}]}}]} as unknown as DocumentNode<CustomDomainQuery, CustomDomainQueryVariables>;