import * as Types from '../../../../../../types/hosting/graphql-base';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type WorkspaceDomainsQueryVariables = Types.Exact<{
  workspaceId: Types.Scalars['ID']['input'];
}>;


export type WorkspaceDomainsQuery = { __typename?: 'Query', workspaceDomains: Array<{ __typename?: 'CustomDomainType', id: string, domain: string, status: Types.WorkspaceHostingCustomDomainStatusChoices, verified: boolean | null, isActive: boolean | null, isPurchasedDomain: boolean | null, canRenew: boolean | null, purchasedViaPlatform: boolean, registrarName: Types.WorkspaceHostingCustomDomainRegistrarNameChoices | null, purchasePriceFcfa: string | null, renewalPriceFcfa: string | null, expiresAt: string | null, nextRenewalDate: string | null, daysUntilExpiry: number | null, isExpiringSoon: boolean | null, renewalReminderSent: boolean, renewalWarningCount: number, sslEnabled: boolean, sslProvisionedAt: string | null, autoRenewEnabled: boolean, createdAt: string, verifiedAt: string | null } | null> | null };


export const WorkspaceDomainsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"WorkspaceDomains"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"workspaceId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"workspaceDomains"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"workspaceId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"workspaceId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"domain"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"verified"}},{"kind":"Field","name":{"kind":"Name","value":"isActive"}},{"kind":"Field","name":{"kind":"Name","value":"isPurchasedDomain"}},{"kind":"Field","name":{"kind":"Name","value":"canRenew"}},{"kind":"Field","name":{"kind":"Name","value":"purchasedViaPlatform"}},{"kind":"Field","name":{"kind":"Name","value":"registrarName"}},{"kind":"Field","name":{"kind":"Name","value":"purchasePriceFcfa"}},{"kind":"Field","name":{"kind":"Name","value":"renewalPriceFcfa"}},{"kind":"Field","name":{"kind":"Name","value":"expiresAt"}},{"kind":"Field","name":{"kind":"Name","value":"nextRenewalDate"}},{"kind":"Field","name":{"kind":"Name","value":"daysUntilExpiry"}},{"kind":"Field","name":{"kind":"Name","value":"isExpiringSoon"}},{"kind":"Field","name":{"kind":"Name","value":"renewalReminderSent"}},{"kind":"Field","name":{"kind":"Name","value":"renewalWarningCount"}},{"kind":"Field","name":{"kind":"Name","value":"sslEnabled"}},{"kind":"Field","name":{"kind":"Name","value":"sslProvisionedAt"}},{"kind":"Field","name":{"kind":"Name","value":"autoRenewEnabled"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"verifiedAt"}}]}}]}}]} as unknown as DocumentNode<WorkspaceDomainsQuery, WorkspaceDomainsQueryVariables>;