import * as Types from '../../../../../../types/workspace/store/graphql-base';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type GetPaymentMethodsQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type GetPaymentMethodsQuery = { __typename?: 'Query', paymentMethods: Array<{ __typename?: 'MerchantPaymentMethodType', id: string, providerName: string, checkoutUrl: string | null, enabled: boolean, verified: boolean, successRate: number | null, displayName: string | null, totalTransactions: number, successfulTransactions: number, lastUsedAt: string | null, createdAt: string, updatedAt: string, capabilities: { __typename?: 'ProviderCapabilitiesType', paymentModes: Array<string | null> | null, supportedCurrencies: Array<string | null> | null, supportsRefunds: boolean | null, supportsWebhooks: boolean | null, displayName: string | null } | null } | null> | null, availableProviders: Array<{ __typename?: 'AvailableProviderType', provider: string, displayName: string, description: string | null, requiresUrl: boolean | null, alreadyAdded: boolean | null } | null> | null };


export const GetPaymentMethodsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetPaymentMethods"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"paymentMethods"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"providerName"}},{"kind":"Field","name":{"kind":"Name","value":"checkoutUrl"}},{"kind":"Field","name":{"kind":"Name","value":"enabled"}},{"kind":"Field","name":{"kind":"Name","value":"verified"}},{"kind":"Field","name":{"kind":"Name","value":"successRate"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}},{"kind":"Field","name":{"kind":"Name","value":"totalTransactions"}},{"kind":"Field","name":{"kind":"Name","value":"successfulTransactions"}},{"kind":"Field","name":{"kind":"Name","value":"lastUsedAt"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"capabilities"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"paymentModes"}},{"kind":"Field","name":{"kind":"Name","value":"supportedCurrencies"}},{"kind":"Field","name":{"kind":"Name","value":"supportsRefunds"}},{"kind":"Field","name":{"kind":"Name","value":"supportsWebhooks"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"availableProviders"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"provider"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"requiresUrl"}},{"kind":"Field","name":{"kind":"Name","value":"alreadyAdded"}}]}}]}}]} as unknown as DocumentNode<GetPaymentMethodsQuery, GetPaymentMethodsQueryVariables>;