import * as Types from '../../../../../../types/hosting/graphql-base';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type DomainRenewalStatusQueryVariables = Types.Exact<{
  renewalId: Types.Scalars['ID']['input'];
}>;


export type DomainRenewalStatusQuery = { __typename?: 'Query', domainRenewalStatus: { __typename?: 'DomainRenewalType', id: string, domainName: string, registrar: string, registrarRenewalId: string | null, renewalPriceFcfa: string, exchangeRate: string, paymentMethod: string, paymentProvider: string | null, renewalStatus: Types.WorkspaceHostingDomainRenewalRenewalStatusChoices, previousExpiryDate: string, newExpiryDate: string | null, renewedAt: string | null, warningSentAt: string | null, daysBeforeExpiryWarned: number | null, isPendingPayment: boolean | null, isCompleted: boolean | null, isFailed: boolean | null, createdAt: string, updatedAt: string } | null };


export const DomainRenewalStatusDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"DomainRenewalStatus"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"renewalId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"domainRenewalStatus"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"renewalId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"renewalId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"domainName"}},{"kind":"Field","name":{"kind":"Name","value":"registrar"}},{"kind":"Field","name":{"kind":"Name","value":"registrarRenewalId"}},{"kind":"Field","name":{"kind":"Name","value":"renewalPriceFcfa"}},{"kind":"Field","name":{"kind":"Name","value":"exchangeRate"}},{"kind":"Field","name":{"kind":"Name","value":"paymentMethod"}},{"kind":"Field","name":{"kind":"Name","value":"paymentProvider"}},{"kind":"Field","name":{"kind":"Name","value":"renewalStatus"}},{"kind":"Field","name":{"kind":"Name","value":"previousExpiryDate"}},{"kind":"Field","name":{"kind":"Name","value":"newExpiryDate"}},{"kind":"Field","name":{"kind":"Name","value":"renewedAt"}},{"kind":"Field","name":{"kind":"Name","value":"warningSentAt"}},{"kind":"Field","name":{"kind":"Name","value":"daysBeforeExpiryWarned"}},{"kind":"Field","name":{"kind":"Name","value":"isPendingPayment"}},{"kind":"Field","name":{"kind":"Name","value":"isCompleted"}},{"kind":"Field","name":{"kind":"Name","value":"isFailed"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}}]}}]}}]} as unknown as DocumentNode<DomainRenewalStatusQuery, DomainRenewalStatusQueryVariables>;