import * as Types from '../../../../../../types/workspace/store/graphql-base';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type GetConversationMessagesQueryVariables = Types.Exact<{
  conversationId: Types.Scalars['ID']['input'];
}>;


export type GetConversationMessagesQuery = { __typename?: 'Query', inboxMessages: { __typename?: 'InboxMessageConnection', edges: Array<{ __typename?: 'InboxMessageEdge', node: { __typename?: 'InboxMessageType', id: string, body: string | null, senderType: Types.WorkspaceInboxInboxMessageSenderTypeChoices, interactiveData: any | null, voiceUrl: string | null, voiceDuration: number | null, voiceWaveform: Array<number | null> | null, mediaType: string | null, mediaMimeType: string | null, latitude: number | null, longitude: number | null, locationName: string | null, locationAddress: string | null, createdAt: string } | null } | null> } | null };


export const GetConversationMessagesDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetConversationMessages"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"conversationId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"inboxMessages"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"conversation"},"value":{"kind":"Variable","name":{"kind":"Name","value":"conversationId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"edges"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"node"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"body"}},{"kind":"Field","name":{"kind":"Name","value":"senderType"}},{"kind":"Field","name":{"kind":"Name","value":"interactiveData"}},{"kind":"Field","name":{"kind":"Name","value":"voiceUrl"}},{"kind":"Field","name":{"kind":"Name","value":"voiceDuration"}},{"kind":"Field","name":{"kind":"Name","value":"voiceWaveform"}},{"kind":"Field","name":{"kind":"Name","value":"mediaType"}},{"kind":"Field","name":{"kind":"Name","value":"mediaMimeType"}},{"kind":"Field","name":{"kind":"Name","value":"latitude"}},{"kind":"Field","name":{"kind":"Name","value":"longitude"}},{"kind":"Field","name":{"kind":"Name","value":"locationName"}},{"kind":"Field","name":{"kind":"Name","value":"locationAddress"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}}]}}]}}]}}]}}]} as unknown as DocumentNode<GetConversationMessagesQuery, GetConversationMessagesQueryVariables>;