import * as Types from '../../../../../../types/workspace/store/graphql-base';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type GetInboxConversationsQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type GetInboxConversationsQuery = { __typename?: 'Query', inboxConversations: { __typename?: 'InboxConversationConnection', edges: Array<{ __typename?: 'InboxConversationEdge', node: { __typename?: 'InboxConversationType', id: string, customerPhone: string, status: Types.WorkspaceInboxInboxConversationStatusChoices, isAiActive: boolean, aiAutonomyMode: Types.AiAutonomyModeEnum | null, unreadCount: number, cartValue: any, updatedAt: string, isStateTransitionPaused: boolean | null, pauseReason: string | null, lastMessage: { __typename?: 'InboxMessageType', id: string, body: string | null, senderType: Types.WorkspaceInboxInboxMessageSenderTypeChoices, interactiveData: any | null, voiceUrl: string | null, voiceDuration: number | null, voiceWaveform: Array<number | null> | null, mediaType: string | null, mediaMimeType: string | null, latitude: number | null, longitude: number | null, locationName: string | null, locationAddress: string | null, createdAt: string } | null, workmanSettings: { __typename?: 'WorkmanSettingsType', llmProvider: Types.WorkmanWorkmanSettingsLlmProviderChoices, autoReplyEnabled: boolean } | null } | null } | null> } | null };


export const GetInboxConversationsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetInboxConversations"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"inboxConversations"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"edges"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"node"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"customerPhone"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"isAiActive"}},{"kind":"Field","name":{"kind":"Name","value":"aiAutonomyMode"}},{"kind":"Field","name":{"kind":"Name","value":"unreadCount"}},{"kind":"Field","name":{"kind":"Name","value":"cartValue"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"lastMessage"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"body"}},{"kind":"Field","name":{"kind":"Name","value":"senderType"}},{"kind":"Field","name":{"kind":"Name","value":"interactiveData"}},{"kind":"Field","name":{"kind":"Name","value":"voiceUrl"}},{"kind":"Field","name":{"kind":"Name","value":"voiceDuration"}},{"kind":"Field","name":{"kind":"Name","value":"voiceWaveform"}},{"kind":"Field","name":{"kind":"Name","value":"mediaType"}},{"kind":"Field","name":{"kind":"Name","value":"mediaMimeType"}},{"kind":"Field","name":{"kind":"Name","value":"latitude"}},{"kind":"Field","name":{"kind":"Name","value":"longitude"}},{"kind":"Field","name":{"kind":"Name","value":"locationName"}},{"kind":"Field","name":{"kind":"Name","value":"locationAddress"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}}]}},{"kind":"Field","name":{"kind":"Name","value":"workmanSettings"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"llmProvider"}},{"kind":"Field","name":{"kind":"Name","value":"autoReplyEnabled"}}]}},{"kind":"Field","name":{"kind":"Name","value":"isStateTransitionPaused"}},{"kind":"Field","name":{"kind":"Name","value":"pauseReason"}}]}}]}}]}}]}}]} as unknown as DocumentNode<GetInboxConversationsQuery, GetInboxConversationsQueryVariables>;