import * as Types from '../../../../../../types/hosting/graphql-base';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type DomainPurchaseStatusQueryVariables = Types.Exact<{
  purchaseId: Types.Scalars['ID']['input'];
}>;


export type DomainPurchaseStatusQuery = { __typename?: 'Query', domainPurchaseStatus: { __typename?: 'DomainPurchaseType', id: string, domainName: string, registrar: Types.WorkspaceHostingDomainPurchaseRegistrarChoices, registrarOrderId: string | null, priceFcfa: string, exchangeRate: string, paymentMethod: string, paymentProvider: string | null, paymentStatus: Types.WorkspaceHostingDomainPurchasePaymentStatusChoices, registrationPeriodYears: number, registeredAt: string | null, expiresAt: string | null, errorMessage: string, isPending: boolean | null, isCompleted: boolean | null, isFailed: boolean | null, createdAt: string, updatedAt: string } | null };


export const DomainPurchaseStatusDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"DomainPurchaseStatus"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"purchaseId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"domainPurchaseStatus"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"purchaseId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"purchaseId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"domainName"}},{"kind":"Field","name":{"kind":"Name","value":"registrar"}},{"kind":"Field","name":{"kind":"Name","value":"registrarOrderId"}},{"kind":"Field","name":{"kind":"Name","value":"priceFcfa"}},{"kind":"Field","name":{"kind":"Name","value":"exchangeRate"}},{"kind":"Field","name":{"kind":"Name","value":"paymentMethod"}},{"kind":"Field","name":{"kind":"Name","value":"paymentProvider"}},{"kind":"Field","name":{"kind":"Name","value":"paymentStatus"}},{"kind":"Field","name":{"kind":"Name","value":"registrationPeriodYears"}},{"kind":"Field","name":{"kind":"Name","value":"registeredAt"}},{"kind":"Field","name":{"kind":"Name","value":"expiresAt"}},{"kind":"Field","name":{"kind":"Name","value":"errorMessage"}},{"kind":"Field","name":{"kind":"Name","value":"isPending"}},{"kind":"Field","name":{"kind":"Name","value":"isCompleted"}},{"kind":"Field","name":{"kind":"Name","value":"isFailed"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}}]}}]}}]} as unknown as DocumentNode<DomainPurchaseStatusQuery, DomainPurchaseStatusQueryVariables>;